START  ADD STEP, PTR
       MOV LOOPE, <PTR
       MOV LOOP, <PTR
       SPL @PTR, 0
       JMP START, 0
BOMB   DAT 0, 0
LOOP   MOV BOMB, <BOMB
LOOPE  JMP LOOP, BOMB
STEP   DAT 250, 250
PTR    DAT 151, 151
